### PR TITLE
Update mypy ignore comments

### LINKED ISSUE #1708: CI failing on mypy step
First started [3 days ago](https://github.com/nextstrain/augur/actions/runs/12612501086/job/35149294996):

```
augur/data/__init__.py:25: error: Cannot find implementation or library stub for module named "importlib_resources"  [import-not-found]
augur/data/__init__.py:2[5](https://github.com/nextstrain/augur/actions/runs/12612501086/job/35149294996#step:5:6): note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked [7](https://github.com/nextstrain/augur/actions/runs/12612501086/job/35149294996#step:5:8)9 source files)
Error: Process completed with exit code 1.
```

Caused by change of runner image from ubuntu-22.04 (Python 3.10.12) to ubuntu-24.04 (Python 3.12.3)

## Possible solution

Tell mypy to ignore the conditional import lines. This is already done elsewhere:

https://github.com/nextstrain/augur/blob/f758ced4f7320078eeb4b63f3e2890a175b48617/augur/filter/include_exclude_rules.py#L17-L21

### PR DESCRIPTION
**Pull request by victorlin**
## Description of proposed changes

Update old ones and add ones that work on Python 3.12.

## Related issue(s)

Closes #1708

## Checklist

- [x] Automated checks pass
- [x] [Check][1] if you need to add a changelog message
- [x] [Check][2] if you need to add tests
- [x] [Check][3] if you need to update docs

[1]: https://github.com/nextstrain/augur/blob/-/docs/contribute/DEV_DOCS.md#updating-the-changelog
[2]: https://github.com/nextstrain/augur/blob/-/docs/contribute/DEV_DOCS.md#testing
[3]: https://github.com/nextstrain/augur/blob/-/docs/contribute/DEV_DOCS.md#when-to-update

### CODE REVIEW

**Comment by victorlin** [comment]
Merging without review for a ✅ CI.
